apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  namespace: clusters
spec:
  repo: https://github.com/kliu513/rancher-fleet-demo
  branch: main
  targetNamespace: default
  paths:
  - helm
  targets:
  - name: demo
    clusterSelector:
      matchLabels:
        app: demo
