helm:
  chart: "./"
targetCustomizations:
- name: ring0
  helm:
    values:
      image:
        tag: 2.7.0
  clusterSelector:
    matchLabels:
      group: ring0
- name: ring1
  helm:
    values:
      image:
        tag: 3.7.0
  clusterSelector:
    matchLabels:
      group: ring1
