helm:
  chart: "./"
targetCustomizations:
- name: ring0
  helm:
    values:
      image:
        tag: 4.0.0
  clusterSelector:
    matchLabels:
      group: ring0
- name: ring1
  helm:
    values:
      image:
        tag: 2.8.0
  clusterSelector:
    matchLabels:
      group: ring1
